version: 2

build:
    os: ubuntu-20.04
    tools:
        python: "3.6"

formats: all

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true

python:
    install:
        - requirements: docs/requirements.txt
